#!/bin/bash

# CV Extraction Debugging Guide

echo "🔍 CV EXTRACTION DEBUGGING CHECKLIST"
echo "===================================="
echo ""

echo "1️⃣  START THE APPLICATION"
echo "   Terminal 1: cd BE && make dev"
echo "   Terminal 2: cd FE && npm run dev"
echo ""

echo "2️⃣  NAVIGATE TO ASSESSMENT SETUP"
echo "   - Go to http://localhost:3000"
echo "   - Login as admin"
echo "   - Click 'Create Assessment'"
echo ""

echo "3️⃣  OPEN BROWSER CONSOLE"
echo "   - Press F12 to open DevTools"
echo "   - Go to Console tab"
echo "   - Clear any existing logs"
echo ""

echo "4️⃣  UPLOAD A CV FILE"
echo "   - Click 'Candidate CV *' field"
echo "   - Select a PDF/DOCX/TXT file"
echo "   - Watch the console for logs"
echo ""

echo "5️⃣  EXPECTED CONSOLE LOGS"
echo "   Look for these messages in order:"
echo ""
echo "   [🚀 CV Extraction] Starting extraction process"
echo "   [📊 CV Extraction] Extracted text length: XXXX"
echo "   [✅ CV Parser] Extracted CV data: {..."
echo "   [📝 Form Update] Old state: {..."
echo "   [📝 Form Update] New state: {...}"
echo "   [🎯 Form State] Current candidateInfo: {...}"
echo ""

echo "6️⃣  CHECK FORM FIELDS"
echo "   After extraction, these fields should be populated:"
echo "   ✓ Candidate Name"
echo "   ✓ Email Address"
echo "   ✓ Phone Number"
echo "   ✓ Location"
echo "   ✓ Current Role"
echo "   ✓ Experience"
echo "   ✓ Education"
echo "   ✓ LinkedIn Profile"
echo "   ✓ GitHub Profile"
echo "   ✓ Portfolio Website"
echo ""

echo "7️⃣  VERIFY VISUAL INDICATORS"
echo "   Auto-filled fields should have 'auto-filled' CSS class"
echo "   Hover over fields to see 'Auto-filled from CV' tooltip"
echo ""

echo "8️⃣  DEBUG: IF NOTHING APPEARS"
echo "   a) Check if onTextExtracted callback is called:"
echo "      Search console for: [FileUpload] Calling onTextExtracted"
echo ""
echo "   b) Check if extractCVData is working:"
echo "      Copy this in console:"
echo "      const cvText = 'John Doe\\nEmail: john@example.com';"
echo "      const result = extractCVData(cvText);"
echo "      console.log(result);"
echo ""
echo "   c) Check if setCandidateInfo is updating:"
echo "      Look for: [📝 Form Update] New state: {..."
echo ""
echo "   d) Check Network Tab:"
echo "      - Look for POST to /candidates/save-cv-data (when you click Submit)"
echo "      - Response should be 201 Created"
echo ""

echo "9️⃣  SAMPLE CV FOR QUICK TEST"
echo "   Create file: test-cv.txt"
echo "   Content:"
echo "   ---"
echo "   John Smith"
echo "   San Francisco, CA 94102"
echo "   Phone: (415) 555-0123"
echo "   Email: john.smith@example.com"
echo "   LinkedIn: linkedin.com/in/john-smith"
echo "   GitHub: github.com/johnsmith"
echo ""
echo "   WORK EXPERIENCE"
echo "   Senior Engineer at TechCorp (2020-present)"
echo "   3 years of experience"
echo ""
echo "   EDUCATION"
echo "   B.S. Computer Science, Stanford University"
echo ""
echo "   SKILLS"
echo "   Python, JavaScript, React, Node.js, AWS"
echo "   ---"
echo ""

echo "🔟  KEY DEBUGGING POINTS"
echo "   1. File text extraction:"
echo "      - PDF via pdfjs-dist"
echo "      - DOCX via mammoth"
echo "      - TXT via file.text()"
echo ""
echo "   2. Regex pattern matching:"
echo "      - Email: [a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
echo "      - Phone: Multiple international formats"
echo "      - Location: 'based in', 'located in', City/State"
echo ""
echo "   3. State update:"
echo "      - candidateInfo state in AssessmentSetupContainer"
echo "      - Passed as prop to CandidateInfoSection"
echo "      - Form inputs display the values"
echo ""

echo ""
echo "✅ IF YOU SEE ALL LOGS AND FIELDS POPULATED = SUCCESS!"
echo ""
